import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import SideBarNav from "./components/SideBarNav";
import MessageBuilder from "./components/MessageBuilder";
import Message from "./components/Message";

const inter = Inter({ subsets: ["latin"] });

export default function TemplateBuilder() {
  return (
    <>
      <Head>
        <title>Connectly Template Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <SideBarNav />
        <MessageBuilder />
        <Message />
      </main>
    </>
  );
}
